import sinon from 'sinon'
import realChalk from 'chalk'

const chalk = {}

chalk.keyword = sinon.fake(color => {
  const colorer = realChalk.keyword(color)
  return sinon.fake(text => colorer(text))
})

export const _reset = () => {
  // Reset all the spies generated by chalk.keyword()
  for (const call of chalk.keyword.getCalls()) {
    call.returnValue.resetHistory()
  }
  // Reset chalk.keyword() itself
  chalk.keyword.resetHistory()
}

export default chalk
