import sinon from 'sinon'

const chalk = {}

chalk.keyword = sinon.fake(() => sinon.fake(() => ''))

export const _reset = () => {
  // Reset all the spies generated by chalk.keyword()
  for (const call of chalk.keyword.getCalls()) {
    call.returnValue.resetHistory()
  }
  // Reset chalk.keyword() itself
  chalk.keyword.resetHistory()
}

export default chalk
